Blog/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('blogs.urls',namespace='blogs')),
]

blogs/urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns =[
    #主页
    url(r'^$',views.index,name='index'),

    #查看博客内容
    url(r'^(?P<note_id>\d+)/$',views.show_note,name='show_note'),

    #添加新的博客内容
    url(r'^new_note/$',views.new_note,name='new_note'),

    #编辑已有内容
    url(r'^edit_note/(?P<note_id>\d+)/$',views.edit_note,name='edit_note'),
    ]

users/urls.py
"""define user's url model"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #log in page
    url(r'^login/$',login,{'template_name':'users/login.html'},name="login"),
    #log out page
    url(r'^logout/$',views.logout_view,name='logout'),
    #register page
    url(r'^register/$',views.register,name='register'),
]

blogs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    """个人博客"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __unicode__(self):
        """返回博客内容"""
        return self.title

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class PostNoteForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title','text']
        labels = {'title':'','text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

blogs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import BlogPost
from .forms import PostNoteForm
def index(request):
    """博客主页"""
    notes = BlogPost.objects.order_by('date_added')
    context = {'notes':notes}
    return render(request,'blogs/index.html',context)

def show_note(request,note_id):
    """显示具体的博客内容"""
    note = get_object_or_404(BlogPost,id=note_id)
    context = {'note':note}
    return render(request,'blogs/show_note.html',context)

@login_required
def new_note(request):
    """添加新帖子"""
    if request.method != 'POST':
        #还没提交数据的时候
        form = PostNoteForm()
    else:
        form = PostNoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.owner = request.user
            new_note.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form':form}
    return render(request,'blogs/new_note.html',context)

@login_required
def edit_note(request,note_id):
    """编辑已有帖子"""
    note = get_object_or_404(BlogPost,id=note_id)

    if note.owner == request.user:
        if request.method != 'POST':
            #初次请求使用已有内容填充表单
            form = PostNoteForm(instance=note)
        else:
            #post提交的数据对数据进行处理
            form = PostNoteForm(instance=note,data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('blogs:index'))

        context = {'note':note,'form':form}
        return render(request,'blogs/edit_note.html',context)
    else:
        raise Http404

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def logout_view(request):
    """log off user"""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

def register(request):
    """register a new user"""
    if request.method != 'POST':
        #show empty registy
        form = UserCreationForm()
    else:
        #process filled out form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #allow user login automatically and redircte to home page
            authenticated_user = authenticate(username=new_user.username,
            password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form':form}
    return render(request,'users/register.html',context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Welcome to Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
  </head>

  <body>

    <!-- Static navbar-->
    <nav class="navbar navbar-default navbar-start-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'blogs:index' %}">Home</a>
        </div>

        <div id="navber" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'blogs:new_note' %}">Add new note</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>

    </nav>
    
    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
          {% block content %}{% endblock content %}
      </div>
    </div><!-- /containet -->
  </body>
</html>

blogs/templates/blogs/edit_note.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit Note</h2>
{% endblock header %}

{% block content %}

  <form method="POST" action="{% url 'blogs:edit_note' note.id %}" class="form" >
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">save changes</button>
      {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block header %}
  <div class="jumbotron">
    <h1>Welcome To My Blog.</h1>
  </div>
{% endblock header %}

{% block content %}
  
  {% for note in notes %}
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3>
          <a href="{% url 'blogs:show_note' note.id %}">{{ note.title }}</a>
          ------{{ note.date_added|date:'M d,Y H:i' }}
        </h3>
      </div>

      <div class="panel-body">
        {{ note.text|truncatewords:3 }}
      </div>

    </div><!-- panel -->

  {% empty %}
    there nothing.
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_note.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new note:</h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'blogs:new_note' %}" class="form" >
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add note</button>
    {% endbuttons %}
  </form>

{% endblock content %}

blogs/templates/blogs/show_note.html
{% extends 'blogs/base.html' %}

{% block header %}
  <h2>
    {{ note.title }}
    <small>
      <a href="{% url 'blogs:edit_note' note.id %}"><button>edit it</button></a>
    </small>
  </h2>
{% endblock header %}

{% block content %}

  <h3>{{ note.text|linebreaks }}</h3>

{% endblock content %}

users/templates/users/login.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in your account.</h2>
{% endblock header %}

{% block content %}

  <form method="POST" action="{% url 'users:login' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">log in</button>
      {% endbuttons %}
      
      <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
  </form>

  {% endblock content %}

users/templates/users/register.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Create your personal account.</h2>
{% endblock header %}

{% block content %}

  <form method="POST" action="{% url 'users:register' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="sumbit">Register</button>
      {% endbuttons %}

      <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
  </form>

{% endblock content %}